export const FETCH_PLAYLIST_REQUEST = "FETCH_PLAYLIST_REQUEST";
export const FETCH_PLAYLIST_SUCCESS = "FETCH_PLAYLIST_SUCCESS";
export const FETCH_PLAYLIST_FAILURE = "FETCH_PLAYLIST_FAILURE";
export const ADD_NEW_PLAYLIST = "ADD_PLAYLIST_REQUEST";
export const ADD_PLAYLIST_REQUEST = "ADD_PLAYLIST_REQUEST";
export const ADD_PLAYLIST_SUCCESS = "ADD_PLAYLIST_SUCCESS";
export const ADD_PLAYLIST_FAILURE = "ADD_PLAYLIST_FAILURE";
