export const LOAD_HOME_VIDEOS = "LOAD_HOME_VIDEOS";
export const LOAD_HOME_VIDEOS_SUCCESS = "LOAD_HOME_VIDEOS_SUCCESS";
export const LOAD_HOME_VIDEOS_FAILURE = "LOAD_HOME_VIDEOS_FAILURE";

export const LOAD_EACH_VIDEO = "LOAD_EACH_VIDEO";
export const LOAD_EACH_VIDEO_SUCCESS = "LOAD_EACH_VIDEO_SUCCESS";
export const LOAD_EACH_VIDEO_FAILURE = "LOAD_EACH_VIDEO_FAILURE";

export const LIKE_VIDEO = "LIKE_VIDEO";
export const LIKE_VIDEO_SUCCESS = "LIKE_VIDEO_SUCCESS";
export const LIKE_VIDEO_FAILURE = "LIKE_VIDEO_FAILURE";

export const UPLOAD_VIDEO = "UPLOAD_VIDEO";
export const UPLOAD_VIDEO_SUCCESS = "UPLOAD_VIDEO_SUCCESS";
export const UPLOAD_VIDEO_FAILURE = "UPLOAD_VIDEO_FAILURE";

export const FETCH_VIDEO_LIKE = "FETCH_VIDEO_LIKE";
export const FETCH_VIDEO_LIKE_SUCCESS = "FETCH_VIDEO_LIKE_SUCCESS";
export const FETCH_VIDEO_LIKE_FAILURE = "FETCH_VIDEO_LIKE_FAILURE";

export const INCREASELIKE = "INCREASELIKE";
export const DECREASELIKE = "DECREASELIKE";
export const INCREASEDISLIKE = "INCREASEDISLIKE";
export const DECREASEDISLIKE = "DECREASEDISLIKE";

export const FETCH_LIKED_VIDEOS = "FETCH_LIKED_VIDEOS";
export const FETCH_LIKED_VIDEOS_SUCCESS = "FETCH_LIKED_VIDEOS_SUCCESS";
export const FETCH_LIKED_VIDEOS_FAILURE = "FETCH_LIKED_VIDEOS_FAILURE";
export const UPDATE_SUBSCRIPTION = "UPDATE_SUBSCRIPTION";
